import { getParsedContext } from "@/lib/generatePrompt";
import { generateRequestId } from "@/lib/utils";
import type { ArtworkRequest, GeneratedConcept } from "@/types";

function formatList(items: string[]): string {
  if (items.length === 0) {
    return "- None extracted";
  }

  return items.map((item) => `- ${item}`).join("\n");
}

export function buildArtworkRequest(
  emailText: string,
  selectedConcept: GeneratedConcept,
): ArtworkRequest {
  const parsed = getParsedContext(emailText);

  return {
    request_id: generateRequestId(),
    received_at: new Date().toISOString(),
    customer: parsed.customer ?? "Tyson Foods",
    urgency: parsed.urgency,
    request_type: parsed.requestType ?? "Artwork Request",
    reference_number: parsed.referenceNumber,
    product: parsed.product,
    label_specifications: {
      size: parsed.size,
      material: parsed.material,
      unwind: parsed.unwind,
      roll_qty: parsed.rollQty,
    },
    colors: {
      spot_colors: parsed.spotColors,
      special_instructions: parsed.colorNotes,
    },
    barcode_requirements: parsed.barcodeRequirements,
    layout_instructions: parsed.layoutInstructions,
    parsed_notes: [
      ...parsed.notes,
      ...parsed.colorInstructions,
      `Selected concept variant: ${selectedConcept.variant}`,
      `Concept prompt summary: ${selectedConcept.prompt.slice(0, 200)}...`,
    ],
  };
}

export function buildDesignBrief(
  request: ArtworkRequest,
  selectedConcept: GeneratedConcept,
): string {
  const { label_specifications: specs, colors } = request;

  return `# Tyson Artwork Design Brief

## Request Summary
| Field | Value |
|-------|-------|
| **Request ID** | ${request.request_id} |
| **Received** | ${new Date(request.received_at).toLocaleString()} |
| **Customer** | ${request.customer} |
| **Urgency** | ${request.urgency.toUpperCase()} |
| **Request Type** | ${request.request_type} |
| **Reference #** | ${request.reference_number ?? "N/A"} |

## Product
${request.product ?? "_Not specified in email — confirm with requester_"}

## Label Specifications
- **Size:** ${specs.size ?? 'Confirm dimensions (e.g., 3.7" x 3.01")'}
- **Material:** ${specs.material ?? "Confirm substrate / face stock"}
- **Unwind:** ${specs.unwind ?? "Confirm unwind direction (#1 / #2 / etc.)"}
- **Roll Qty:** ${specs.roll_qty ?? "Per PO / confirm with planner"}

## Colors
### Spot Colors
${formatList(colors.spot_colors)}

### Color Notes
${colors.special_instructions ?? "_No special color instructions extracted_"}

## Barcode Requirements
${request.barcode_requirements ?? "Include GS1 DataMatrix / 2D matrix with required quiet zone per Tyson spec."}

## Layout Instructions
${request.layout_instructions ?? "_Refer to source email and selected concept for layout guidance_"}

## Selected Concept
- **Variant:** Concept ${selectedConcept.variant}
- **Status:** Approved for prepress development (V1 intake)

## Additional Notes
${formatList(request.parsed_notes)}

---
_Generated by Tyson Artwork Tool V1 — review all fields before sending to prepress._
`;
}

export function generateOutput(
  emailText: string,
  selectedConcept: GeneratedConcept,
): { artworkRequest: ArtworkRequest; designBrief: string } {
  const artworkRequest = buildArtworkRequest(emailText, selectedConcept);
  const designBrief = buildDesignBrief(artworkRequest, selectedConcept);

  return { artworkRequest, designBrief };
}
